# Site settings
title: SeaHorn 
tagline: 'SeaHorn'
email: lememta@gmail.com
description: 'SeaHorn Blog'
baseurl: ""
url: "http://seahorn.github.io/blog"

author:
  name:           'SeaHorn'
  url:            http://seahorn.github.io/blog

# Build settings
markdown: kramdown
permalink: pretty

paginate:         5

gems:
  - jekyll-sitemap

